global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "python-ai-mother-backend"
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8123
        labels:
          service: backend
